import type { AnalysisResult } from './types';

function statusLabel(s: string) {
  return s.toUpperCase();
}

function now() {
  return new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
}

function reportRows(results: AnalysisResult[]) {
  return results.map(r => ({
    Product:                r.product,
    'Current Stock':        r.currentStock,
    'Avg Daily Sales':      +r.avgDailySales.toFixed(1),
    'Days Remaining':       Math.round(r.daysRemaining),
    'Days Until Reorder':   Math.round(r.daysUntilReorder),
    'Recommended Order Qty': Math.round(r.reorderQty),
    Status:                 statusLabel(r.status),
    'Data Source':          r.dataSource.toUpperCase(),
  }));
}

/* ── EXCEL ── */
export async function exportExcel(results: AnalysisResult[]) {
  const XLSX = await import('xlsx');

  const wb = XLSX.utils.book_new();

  /* Summary sheet */
  const rows = reportRows(results);
  const ws = XLSX.utils.json_to_sheet(rows);

  /* Column widths */
  ws['!cols'] = [32, 16, 20, 18, 20, 24, 12, 14].map(w => ({ wch: w }));

  XLSX.utils.book_append_sheet(wb, ws, 'Summary');

  /* Priority sheet */
  const urgent = rows.filter(r => r.Status === 'URGENT');
  if (urgent.length) {
    const ws2 = XLSX.utils.json_to_sheet(urgent);
    ws2['!cols'] = ws['!cols'];
    XLSX.utils.book_append_sheet(wb, ws2, 'Priority Reorders');
  }

  XLSX.writeFile(wb, 'inventory_report.xlsx');
}

/* ── PDF ── */
export async function exportPDF(results: AnalysisResult[]) {
  const { default: jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  /* Title */
  doc.setFontSize(20); doc.setTextColor(13, 27, 46);
  doc.text('inventory.ai', 14, 18);
  doc.setFontSize(9); doc.setTextColor(100, 116, 139);
  doc.text(`Inventory Intelligence Report  ·  ${now()}`, 14, 24);

  /* KPI row */
  const urgent  = results.filter(r => r.status === 'urgent').length;
  const warning = results.filter(r => r.status === 'warning').length;
  const healthy = results.filter(r => r.status === 'healthy').length;

  autoTable(doc, {
    startY: 30,
    head: [['TOTAL', 'URGENT', 'WARNING', 'HEALTHY']],
    body: [[results.length, urgent, warning, healthy]],
    styles: { halign: 'center', fontSize: 14, fontStyle: 'bold' },
    headStyles: { fillColor: [27, 58, 107], textColor: 255, fontSize: 8 },
    columnStyles: {
      0: { fillColor: [239, 246, 255] },
      1: { fillColor: [254, 226, 226], textColor: [220, 38, 38] },
      2: { fillColor: [254, 243, 199], textColor: [217, 119, 6] },
      3: { fillColor: [209, 250, 229], textColor: [5, 150, 105] },
    },
    margin: { left: 14, right: 14 },
  });

  /* Main table */
  const rows = reportRows(results);
  const statusColors: Record<string, [number, number, number]> = {
    URGENT:  [254, 226, 226],
    WARNING: [254, 243, 199],
    HEALTHY: [209, 250, 229],
  };

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 8,
    head: [Object.keys(rows[0])],
    body: rows.map(r => Object.values(r)),
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [27, 58, 107], textColor: 255, fontStyle: 'bold' },
    bodyStyles: { textColor: [15, 23, 42] },
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === 6) {
        const val = String(data.cell.raw);
        data.cell.styles.fillColor = statusColors[val] ?? [255, 255, 255];
        data.cell.styles.fontStyle = 'bold';
      }
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 14, right: 14 },
  });

  /* Footer */
  doc.setFontSize(8); doc.setTextColor(148, 163, 184);
  doc.text('Generated by inventory.ai  ·  Confidential', 148.5, doc.internal.pageSize.height - 8, { align: 'center' });

  doc.save('inventory_report.pdf');
}

/* ── WORD ── */
export async function exportWord(results: AnalysisResult[]) {
  const { Document, Packer, Paragraph, Table, TableRow, TableCell,
          TextRun, WidthType, AlignmentType, HeadingLevel,
          BorderStyle, ShadingType } = await import('docx');

  const urgent  = results.filter(r => r.status === 'urgent').length;
  const warning = results.filter(r => r.status === 'warning').length;
  const healthy = results.filter(r => r.status === 'healthy').length;

  const NAVY = '0D1B2E'; const RED = 'FEE2E2'; const AMB = 'FEF3C7'; const GRN = 'D1FAE5';
  const HDR  = '1B3A6B';

  function cell(text: string, bold = false, bg?: string, color = '0F172A') {
    return new TableCell({
      shading: bg ? { type: ShadingType.CLEAR, fill: bg } : undefined,
      children: [new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: String(text), bold, color, size: 18 })],
      })],
    });
  }

  const rows = reportRows(results);
  const headers = Object.keys(rows[0]);

  const statusBg: Record<string, string> = { URGENT: RED, WARNING: AMB, HEALTHY: GRN };

  const tableRows = [
    new TableRow({
      children: headers.map(h => new TableCell({
        shading: { type: ShadingType.CLEAR, fill: HDR },
        children: [new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: h, bold: true, color: 'FFFFFF', size: 16 })],
        })],
      })),
    }),
    ...rows.map(row => new TableRow({
      children: Object.entries(row).map(([k, v]) =>
        cell(String(v), k === 'Status', statusBg[String(v)] ?? undefined)
      ),
    })),
  ];

  const doc = new Document({
    sections: [{
      children: [
        new Paragraph({ text: 'inventory.ai', heading: HeadingLevel.TITLE }),
        new Paragraph({
          children: [new TextRun({ text: `Inventory Intelligence Report  ·  ${now()}`, color: '94A3B8', size: 18 })],
        }),
        new Paragraph({ text: '' }),
        new Paragraph({ text: 'KPI Summary', heading: HeadingLevel.HEADING_2 }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: ['TOTAL PRODUCTS','URGENT','WARNING','HEALTHY'].map(h => cell(h, true)) }),
            new TableRow({ children: [results.length, urgent, warning, healthy].map(v => cell(String(v), true)) }),
          ],
        }),
        new Paragraph({ text: '' }),
        new Paragraph({ text: 'Full Inventory Recommendations', heading: HeadingLevel.HEADING_2 }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: tableRows,
        }),
        new Paragraph({ text: '' }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: 'Generated by inventory.ai  ·  Confidential', color: '94A3B8', size: 16 })],
        }),
      ],
    }],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = 'inventory_report.docx'; a.click();
  URL.revokeObjectURL(url);
}
